BEGIN
    pizza.INSTALARE_TRIGGERI_AUTOGENERAT();
END;
/

CREATE OR REPLACE TRIGGER limita_angajati
    FOR INSERT OR DELETE OR UPDATE ON angajat
    COMPOUND TRIGGER

    BEFORE STATEMENT
    IS
    BEGIN
        LOCK TABLE aux_lim_ang IN EXCLUSIVE MODE;
    END BEFORE STATEMENT;

    BEFORE EACH ROW
    IS
    BEGIN
        pizza.IMPL_TRIGGER_LIMITA_ANGAJATI_PER_ROW(:OLD.id_restaurant, :NEW.id_restaurant);
    END BEFORE EACH ROW;
END;
/

CREATE OR REPLACE TRIGGER protectie_tabele
    BEFORE DDL ON THEO.SCHEMA
BEGIN
    pizza.IMPL_TRIGGER_PROTECTIE_TABELE_DDL();
END;
/
